title: "Naga Dheeraj Biddala - DevOps Engineer"
description: "Explore my resume and professional journey as a DevOps Engineer. Discover my skills, work experience, and more."
theme: minima  # You can replace 'minima' with any other GitHub-supported Jekyll theme